// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIKeyIntegrationConfigs - Decrypted Key/Value object of the associated configuration for that provider
type APIKeyIntegrationConfigs struct {
	APIKey    string `json:"api_key"`
	HeaderKey string `json:"header_key"`
}
