// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeliveryIssueReference - Reference to the event and attempt an issue is being created for.
type DeliveryIssueReference struct {
	AttemptID string `json:"attempt_id"`
	EventID   string `json:"event_id"`
}
