// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DestinationAuthMethodBearerTokenConfig - Bearer token config for the destination's auth method
type DestinationAuthMethodBearerTokenConfig struct {
	// Token for the bearer token auth
	Token string `json:"token"`
}

func (o *DestinationAuthMethodBearerTokenConfig) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}
