// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// IssueTriggerIntegrationChannel - Integration channel for an issue trigger
type IssueTriggerIntegrationChannel struct {
}
