// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RetriedEvent struct {
	Attempt *EventAttempt `json:"attempt"`
	Event   Event         `json:"event"`
}

func (o *RetriedEvent) GetAttempt() *EventAttempt {
	if o == nil {
		return nil
	}
	return o.Attempt
}

func (o *RetriedEvent) GetEvent() Event {
	if o == nil {
		return Event{}
	}
	return o.Event
}
