// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RetryRequest struct {
	Events  []Event `json:"events,omitempty"`
	Request Request `json:"request"`
}

func (o *RetryRequest) GetEvents() []Event {
	if o == nil {
		return nil
	}
	return o.Events
}

func (o *RetryRequest) GetRequest() Request {
	if o == nil {
		return Request{}
	}
	return o.Request
}
