// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"hashicups/internal/sdk/pkg/utils"
)

type SeekPaginationDir struct {
	Schema *OrderByDirection `json:"schema,omitempty"`
}

func (o *SeekPaginationDir) GetSchema() *OrderByDirection {
	if o == nil {
		return nil
	}
	return o.Schema
}

type SeekPaginationOrderByType string

const (
	SeekPaginationOrderByTypeStr        SeekPaginationOrderByType = "str"
	SeekPaginationOrderByTypeArrayOfstr SeekPaginationOrderByType = "arrayOfstr"
)

type SeekPaginationOrderBy struct {
	Str        *string
	ArrayOfstr []string

	Type SeekPaginationOrderByType
}

func CreateSeekPaginationOrderByStr(str string) SeekPaginationOrderBy {
	typ := SeekPaginationOrderByTypeStr

	return SeekPaginationOrderBy{
		Str:  &str,
		Type: typ,
	}
}

func CreateSeekPaginationOrderByArrayOfstr(arrayOfstr []string) SeekPaginationOrderBy {
	typ := SeekPaginationOrderByTypeArrayOfstr

	return SeekPaginationOrderBy{
		ArrayOfstr: arrayOfstr,
		Type:       typ,
	}
}

func (u *SeekPaginationOrderBy) UnmarshalJSON(data []byte) error {

	str := new(string)
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = str
		u.Type = SeekPaginationOrderByTypeStr
		return nil
	}

	arrayOfstr := []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfstr, "", true, true); err == nil {
		u.ArrayOfstr = arrayOfstr
		u.Type = SeekPaginationOrderByTypeArrayOfstr
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u SeekPaginationOrderBy) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfstr != nil {
		return utils.MarshalJSON(u.ArrayOfstr, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type SeekPagination struct {
	Dir     *SeekPaginationDir     `json:"dir,omitempty"`
	Limit   *int64                 `json:"limit,omitempty"`
	Next    *string                `json:"next,omitempty"`
	OrderBy *SeekPaginationOrderBy `json:"order_by,omitempty"`
	Prev    *string                `json:"prev,omitempty"`
}

func (o *SeekPagination) GetDir() *SeekPaginationDir {
	if o == nil {
		return nil
	}
	return o.Dir
}

func (o *SeekPagination) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *SeekPagination) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *SeekPagination) GetOrderBy() *SeekPaginationOrderBy {
	if o == nil {
		return nil
	}
	return o.OrderBy
}

func (o *SeekPagination) GetPrev() *string {
	if o == nil {
		return nil
	}
	return o.Prev
}
