// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
)

type ShortEventDataBody2 struct {
}

type ShortEventDataBodyType string

const (
	ShortEventDataBodyTypeStr                 ShortEventDataBodyType = "str"
	ShortEventDataBodyTypeShortEventDataBody2 ShortEventDataBodyType = "ShortEventData_body_2"
	ShortEventDataBodyTypeArrayOfany          ShortEventDataBodyType = "arrayOfany"
)

type ShortEventDataBody struct {
	Str                 *string
	ShortEventDataBody2 *ShortEventDataBody2
	ArrayOfany          []interface{}

	Type ShortEventDataBodyType
}

func CreateShortEventDataBodyStr(str string) ShortEventDataBody {
	typ := ShortEventDataBodyTypeStr

	return ShortEventDataBody{
		Str:  &str,
		Type: typ,
	}
}

func CreateShortEventDataBodyShortEventDataBody2(shortEventDataBody2 ShortEventDataBody2) ShortEventDataBody {
	typ := ShortEventDataBodyTypeShortEventDataBody2

	return ShortEventDataBody{
		ShortEventDataBody2: &shortEventDataBody2,
		Type:                typ,
	}
}

func CreateShortEventDataBodyArrayOfany(arrayOfany []interface{}) ShortEventDataBody {
	typ := ShortEventDataBodyTypeArrayOfany

	return ShortEventDataBody{
		ArrayOfany: arrayOfany,
		Type:       typ,
	}
}

func (u *ShortEventDataBody) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	str := new(string)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&str); err == nil {
		u.Str = str
		u.Type = ShortEventDataBodyTypeStr
		return nil
	}

	shortEventDataBody2 := new(ShortEventDataBody2)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&shortEventDataBody2); err == nil {
		u.ShortEventDataBody2 = shortEventDataBody2
		u.Type = ShortEventDataBodyTypeShortEventDataBody2
		return nil
	}

	arrayOfany := []interface{}{}
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&arrayOfany); err == nil {
		u.ArrayOfany = arrayOfany
		u.Type = ShortEventDataBodyTypeArrayOfany
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ShortEventDataBody) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return json.Marshal(u.Str)
	}

	if u.ShortEventDataBody2 != nil {
		return json.Marshal(u.ShortEventDataBody2)
	}

	if u.ArrayOfany != nil {
		return json.Marshal(u.ArrayOfany)
	}

	return nil, nil
}

type ShortEventDataHeadersType string

const (
	ShortEventDataHeadersTypeStr      ShortEventDataHeadersType = "str"
	ShortEventDataHeadersTypeMapOfstr ShortEventDataHeadersType = "mapOfstr"
)

type ShortEventDataHeaders struct {
	Str      *string
	MapOfstr map[string]string

	Type ShortEventDataHeadersType
}

func CreateShortEventDataHeadersStr(str string) ShortEventDataHeaders {
	typ := ShortEventDataHeadersTypeStr

	return ShortEventDataHeaders{
		Str:  &str,
		Type: typ,
	}
}

func CreateShortEventDataHeadersMapOfstr(mapOfstr map[string]string) ShortEventDataHeaders {
	typ := ShortEventDataHeadersTypeMapOfstr

	return ShortEventDataHeaders{
		MapOfstr: mapOfstr,
		Type:     typ,
	}
}

func (u *ShortEventDataHeaders) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	str := new(string)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&str); err == nil {
		u.Str = str
		u.Type = ShortEventDataHeadersTypeStr
		return nil
	}

	mapOfstr := map[string]string{}
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&mapOfstr); err == nil {
		u.MapOfstr = mapOfstr
		u.Type = ShortEventDataHeadersTypeMapOfstr
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ShortEventDataHeaders) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return json.Marshal(u.Str)
	}

	if u.MapOfstr != nil {
		return json.Marshal(u.MapOfstr)
	}

	return nil, nil
}

type ShortEventDataParsedQuery2 struct {
}

type ShortEventDataParsedQueryType string

const (
	ShortEventDataParsedQueryTypeStr                        ShortEventDataParsedQueryType = "str"
	ShortEventDataParsedQueryTypeShortEventDataParsedQuery2 ShortEventDataParsedQueryType = "ShortEventData_parsed_query_2"
)

type ShortEventDataParsedQuery struct {
	Str                        *string
	ShortEventDataParsedQuery2 *ShortEventDataParsedQuery2

	Type ShortEventDataParsedQueryType
}

func CreateShortEventDataParsedQueryStr(str string) ShortEventDataParsedQuery {
	typ := ShortEventDataParsedQueryTypeStr

	return ShortEventDataParsedQuery{
		Str:  &str,
		Type: typ,
	}
}

func CreateShortEventDataParsedQueryShortEventDataParsedQuery2(shortEventDataParsedQuery2 ShortEventDataParsedQuery2) ShortEventDataParsedQuery {
	typ := ShortEventDataParsedQueryTypeShortEventDataParsedQuery2

	return ShortEventDataParsedQuery{
		ShortEventDataParsedQuery2: &shortEventDataParsedQuery2,
		Type:                       typ,
	}
}

func (u *ShortEventDataParsedQuery) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	str := new(string)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&str); err == nil {
		u.Str = str
		u.Type = ShortEventDataParsedQueryTypeStr
		return nil
	}

	shortEventDataParsedQuery2 := new(ShortEventDataParsedQuery2)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&shortEventDataParsedQuery2); err == nil {
		u.ShortEventDataParsedQuery2 = shortEventDataParsedQuery2
		u.Type = ShortEventDataParsedQueryTypeShortEventDataParsedQuery2
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ShortEventDataParsedQuery) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return json.Marshal(u.Str)
	}

	if u.ShortEventDataParsedQuery2 != nil {
		return json.Marshal(u.ShortEventDataParsedQuery2)
	}

	return nil, nil
}

type ShortEventData struct {
	Body           *ShortEventDataBody        `json:"body,omitempty"`
	Headers        *ShortEventDataHeaders     `json:"headers,omitempty"`
	IsLargePayload *bool                      `json:"is_large_payload,omitempty"`
	ParsedQuery    *ShortEventDataParsedQuery `json:"parsed_query,omitempty"`
	Path           string                     `json:"path"`
	Query          *string                    `json:"query,omitempty"`
}
