// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SourcePaginatedResult struct {
	Count      *int64          `json:"count,omitempty"`
	Models     []Source        `json:"models,omitempty"`
	Pagination *SeekPagination `json:"pagination,omitempty"`
}

func (o *SourcePaginatedResult) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *SourcePaginatedResult) GetModels() []Source {
	if o == nil {
		return nil
	}
	return o.Models
}

func (o *SourcePaginatedResult) GetPagination() *SeekPagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}
