// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TransformationExecutionPaginatedResult - List of transformation executions
type TransformationExecutionPaginatedResult struct {
	Count      *int64                    `json:"count,omitempty"`
	Models     []TransformationExecution `json:"models,omitempty"`
	Pagination *SeekPagination           `json:"pagination,omitempty"`
}
