// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Transformation - A single transformation
type Transformation struct {
	// JavaScript code to be executed
	Code string `json:"code"`
	// Date the transformation was created
	CreatedAt    time.Time `json:"created_at"`
	EncryptedEnv *string   `json:"encrypted_env,omitempty"`
	// Key-value environment variables to be passed to the transformation
	Env map[string]string `json:"env,omitempty"`
	// ID of the transformation
	ID string  `json:"id"`
	Iv *string `json:"iv,omitempty"`
	// A unique, human-friendly name for the transformation
	Name string `json:"name"`
	// ID of the workspace
	TeamID string `json:"team_id"`
	// Date the transformation was last updated
	UpdatedAt time.Time `json:"updated_at"`
}
