// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type BasicAuth1 struct {
	Config *DestinationAuthMethodBasicAuthConfig1 `tfsdk:"config"`
	Type   types.String                           `tfsdk:"type"`
}
