// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type Rule1 struct {
	AlertRule     *AlertRule     `tfsdk:"alert_rule"`
	DelayRule     *DelayRule     `tfsdk:"delay_rule"`
	FilterRule    *FilterRule1   `tfsdk:"filter_rule"`
	RetryRule     *RetryRule     `tfsdk:"retry_rule"`
	TransformRule *TransformRule `tfsdk:"transform_rule"`
}
