// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type FilterRule2 struct {
	Body    *ConnectionFilterProperty9  `tfsdk:"body"`
	Headers *ConnectionFilterProperty10 `tfsdk:"headers"`
	Path    *ConnectionFilterProperty11 `tfsdk:"path"`
	Query   *ConnectionFilterProperty12 `tfsdk:"query"`
	Type    types.String                `tfsdk:"type"`
}
