// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type IssueTriggerReference struct {
	IssueTriggerBackpressureConfigs   *IssueTriggerBackpressureConfigs   `tfsdk:"issue_trigger_backpressure_configs"`
	IssueTriggerDeliveryConfigs       *IssueTriggerDeliveryConfigs       `tfsdk:"issue_trigger_delivery_configs"`
	IssueTriggerTransformationConfigs *IssueTriggerTransformationConfigs `tfsdk:"issue_trigger_transformation_configs"`
}
