// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type FilterRule5 struct {
	Body    *ConnectionFilterProperty21 `tfsdk:"body"`
	Headers *ConnectionFilterProperty22 `tfsdk:"headers"`
	Path    *ConnectionFilterProperty23 `tfsdk:"path"`
	Query   *ConnectionFilterProperty24 `tfsdk:"query"`
	Type    types.String                `tfsdk:"type"`
}
