// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type IssueTriggerDeliveryConfigsConnections1 struct {
	Str        types.String   `tfsdk:"str"`
	ArrayOfstr []types.String `tfsdk:"array_ofstr"`
}
