// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type DestinationAuthMethodBearerTokenConfig1 struct {
	Token types.String `tfsdk:"token"`
}
