// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hashicups/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteDestinationRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

// DeleteDestination200ApplicationJSON - A single destination
type DeleteDestination200ApplicationJSON struct {
	// ID of the destination
	ID string `json:"id"`
}

type DeleteDestinationResponse struct {
	// Not Found
	APIErrorResponse *shared.APIErrorResponse
	ContentType      string
	StatusCode       int
	RawResponse      *http.Response
	// A single destination
	DeleteDestination200ApplicationJSONObject *DeleteDestination200ApplicationJSON
}
