// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hashicups/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetBookmarkRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetBookmarkResponse struct {
	// Not Found
	APIErrorResponse *shared.APIErrorResponse
	// A single bookmark
	Bookmark    *shared.Bookmark
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
