// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hashicups/internal/sdk/pkg/models/shared"
	"net/http"
)

type ToggleWebhookNotificationsRequestBody struct {
	// Enable or disable webhook notifications on the workspace
	Enabled *bool `json:"enabled,omitempty"`
	// The Hookdeck Source to send the webhook to
	SourceID *string `json:"source_id,omitempty"`
	// List of topics to send notifications for
	Topics []shared.TopicsValue `json:"topics,omitempty"`
}

type ToggleWebhookNotificationsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Toggle operation status response
	ToggleWebhookNotifications *shared.ToggleWebhookNotifications
}
