// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hashicups/internal/sdk/pkg/models/shared"
	"net/http"
)

type UnarchiveDestinationRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UnarchiveDestinationRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type UnarchiveDestinationResponse struct {
	// Not Found
	APIErrorResponse *shared.APIErrorResponse
	// HTTP response content type for this operation
	ContentType string
	// A single destination
	Destination *shared.Destination
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UnarchiveDestinationResponse) GetAPIErrorResponse() *shared.APIErrorResponse {
	if o == nil {
		return nil
	}
	return o.APIErrorResponse
}

func (o *UnarchiveDestinationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UnarchiveDestinationResponse) GetDestination() *shared.Destination {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *UnarchiveDestinationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UnarchiveDestinationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
