// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hashicups/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateBookmarkRequestBody struct {
	// ID of the event data to bookmark
	EventDataID *string `json:"event_data_id,omitempty"`
	// Descriptive name of the bookmark
	Label *string `json:"label,omitempty"`
	// A unique, human-friendly name for the bookmark
	Name *string `json:"name,omitempty"`
	// ID of the associated connection
	WebhookID *string `json:"webhook_id,omitempty"`
}

type UpdateBookmarkRequest struct {
	RequestBody UpdateBookmarkRequestBody `request:"mediaType=application/json"`
	ID          string                    `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateBookmarkResponse struct {
	// Bad Request
	APIErrorResponse *shared.APIErrorResponse
	// A single bookmark
	Bookmark    *shared.Bookmark
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
